### ISSUE TITLE
Take a look at mod called "Mapmaker's Gadgets"

### ISSUE THREAD

**Issue by ilKestrelHawkli** [mando222/NomadsRPG#45]

**Comment by mando222** [comment]
@ilKestrelHawkli I think this is our best shot at the unbreaking beds and the like.

**Comment by ilKestrelHawkli** [comment]
I'll play around with this

**Comment by ilKestrelHawkli** [comment]
It creates a unique placeable item, it doesn't change the properties of all beds. Also, the unbreaking attribute applies to tools and does nothing to prevent blocks from being broken

**Comment by mando222** [comment]
not doing
