### ISSUE TITLE
Look into evil craft

### ISSUE THREAD

**Issue by mando222** [mando222/NomadsRPG#48]
https://www.curseforge.com/minecraft/mc-mods/evilcraft

**Comment by mando222** [comment]
@ilKestrelHawkli I think we should add this.  It looks like something that would add to gameplay.

**Comment by ilKestrelHawkli** [comment]
@mando222 Let's talk about this too, it looks to me like it requires too much building to really do anything and I don't see anything that compelling in it

**Comment by mando222** [comment]
need something different.
