### ISSUE TITLE
invincible mobs

### ISSUE THREAD

**Issue by mando222** [mando222/NomadsRPG#56]
All mobs are invincible.

Didn't see anything in the logs but here they are for now https://gist.github.com/mando222/3b869c102646edd9272045874aedf104

**Comment by mando222** [comment]
This was confirmed by all three testers.

**Comment by mando222** [comment]
Idea could this be the difficulty going up to a crazy level without showing on the bar correctly.  Would this in theory make the mobs invincible?

**Comment by ilKestrelHawkli** [comment]
Yeah, i currently have the difficulty scaling at an unrealistic level to more easily see the effects of distance and time manipulators

**Comment by ilKestrelHawkli** [comment]
readjusted difficulty curve.
