### ISSUE TITLE
Add Craftable Horse Armor and Saddles

### ISSUE THREAD

**Issue by ilKestrelHawkli** [mando222/NomadsRPG#66]

**Comment by ilKestrelHawkli** [comment]
Unless we think that the saddles are common enough loot

**Comment by mando222** [comment]
We can always remove them from the loot tables.

**Comment by ilKestrelHawkli** [comment]
We can talk about it, I can see both ways. Having them just be loot potentially keeps players from instantly getting the ability to move very fast.

**Comment by mando222** [comment]
not doing that
